name: Deploy

on: push

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Get into the code
        uses: actions/checkout@v2

      - name: Install the dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          keep_files: true
